FROM ubuntu
RUN apt-get update
RUN apt-get -y install wget
RUN apt-get -y install python3
RUN apt-get -y install pip
RUN wget https://github.com/h2oai/wave/releases/download/v0.22.0/wave-0.22.0-linux-amd64.tar.gz
RUN tar -xvf wave-0.22.0-linux-amd64.tar.gz && mv wave-0.22.0-linux-amd64 /wave
RUN chmod +x /wave/waved
RUN pip install h2o-wave
RUN pip install requests
WORKDIR /wave

COPY . .

EXPOSE 10101/tcp
CMD ["sh", "start.sh"]