FROM python:3.10.4

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade -r /code/requirements.txt
RUN python -m spacy download en_core_web_sm

COPY . .

EXPOSE 8000/tcp

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]